name: Nokia N-Gage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout toolchain
      uses: actions/checkout@v4

    - name: Install Ninja
      run: choco install ninja --confirm
      shell: pwsh

    - name: Clone ngage-toolchain
      run: git clone https://github.com/ngagesdk/ngage-toolchain.git

    - name: Set up NGAGESDK environment variable
      run: |
        $ngagesdk = "${{ github.workspace }}/ngage-toolchain"
        $ngagesdk = $ngagesdk -replace '\\', '/'
        echo "NGAGESDK=$ngagesdk" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Add runtime paths to PATH
      run: |
        echo "${{ env.NGAGESDK }}/sdk/sdk/6.1/Shared/EPOC32/gcc/bin" >> $env:GITHUB_PATH
        echo "${{ env.NGAGESDK }}/sdk/sdk/6.1/Shared/EPOC32/ngagesdk/bin" >> $env:GITHUB_PATH
      shell: pwsh

    - name: Verify directory structure
      run: |
        echo "NGAGESDK: ${{ env.NGAGESDK }}"
        ls ${{ env.NGAGESDK }}
        ls ${{ env.NGAGESDK }}/setup
      shell: pwsh

    - name: Fetch SDK
      run: cmake -G "Ninja" -P ${{ env.NGAGESDK }}/setup/setup.cmake -S ${{ env.NGAGESDK }}/setup -B ${{ env.NGAGESDK }}/build
      shell: pwsh

    - name: Clone ncore
      run: git clone https://github.com/mupfdev/ncore.git ${{ env.NGAGESDK }}/projects/ncore
      shell: pwsh

    - name: Build ncore
      run: |
        cmake -DCMAKE_PREFIX_PATH=${{ env.NGAGESDK }}/sdk/extras/lib/cmake -G "Ninja" -S ${{ env.NGAGESDK }}/projects/ncore -B ${{ env.NGAGESDK }}/projects/ncore/build -DCMAKE_TOOLCHAIN_FILE=${{ env.NGAGESDK }}/cmake/ngage-toolchain.cmake
        cmake --build ${{ env.NGAGESDK }}/projects/ncore/build
      shell: pwsh

    - name: Prepare ncore artifact directory
      run: |
        New-Item -ItemType Directory -Path System\Apps\ncore -Force
        Copy-Item build\ncore.aif System\Apps\ncore\
        Copy-Item build\ncore.app System\Apps\ncore\
        Copy-Item build\ncore.exe System\Apps\ncore\
        Copy-Item build\ncore.rsc System\Apps\ncore\
        Copy-Item export\data.pfs System\Apps\ncore\
      shell: pwsh

    - name: Archive ncore
      uses: actions/upload-artifact@v4
      with:
        name: ncore-NGAGE.zip
        path: System
        if-no-files-found: error
